# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-03 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField(verbose_name='Roll Number')),
                ('name', models.CharField(max_length=56, verbose_name='Name')),
                ('marks', models.IntegerField(verbose_name='Marks')),
                ('grade', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='b', max_length=90, verbose_name='Grade')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
